name : deploy of laravel project to cpanel
on:
  watch:
    - main
jobs:
  web-deploy:
    name : deploy
    runs-on: ubuntu-latest
    steps:
      - name: get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example','.env');"
      - name: install dependencies
        run: composer update --ignore-platform-reqs
      - name: generate key
        run: php artisan key:generate
      - name: generate storage link
        run: php artisan storage:link
      - name: directory permissions
        run: chmod -R 777 storage/cache
      - name: Sync files
        uses: Samkirland/FTP-Deploy-Action@4.0.0
        with:
            server: ${{ secrets.CPANEL_HOST }}
            USERNAME: ${{ secrets.CPANEL_USERNAME }}
            PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
            server-dir: /
            
            
        
